#!/usr/bin/env python3

import argparse
import rclpy
import time

from lifecycle_msgs.msg import Transition
from lifecycle_msgs.srv import ChangeState


def main(args=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--namespace', type=str, default='')
    parser.add_argument('--node', type=str, default='node_name')
    parser.add_argument('--auto_configure', type=bool, default=True)
    parser.add_argument('--auto_activate', type=bool, default=True)
    parser.add_argument('--timeout', type=float, default=5.0)
    parser.add_argument('--transition_attempts', type=int, default=3)
    arg, _ = parser.parse_known_args(args=args)

    print(arg)

    rclpy.init()
    node = rclpy.create_node(f'activate_{arg.node}')

    cli = node.create_client(
        ChangeState,
        f'/{arg.namespace}/'
        f'{arg.node}/change_state')
    if not cli.wait_for_service(timeout_sec=arg.timeout):
        node.get_logger().error('Lifecycle service not available.')
        return

    retry_count = int(arg.transition_attempts)
    req = ChangeState.Request()

    if arg.auto_configure:
        req.transition.id = Transition.TRANSITION_CONFIGURE
        for i in range(retry_count):
            future = cli.call_async(req)
            rclpy.spin_until_future_complete(node, future)
            if future.result() and future.result().success:
                node.get_logger().info('Lifecycle node configured successfully.')
                break
            else:
                node.get_logger().warn(f'Activation attempt {i+1} failed. Retrying...')
                time.sleep(arg.timeout)

    if arg.auto_activate:
        req.transition.id = Transition.TRANSITION_ACTIVATE
        for i in range(retry_count):
            future = cli.call_async(req)
            rclpy.spin_until_future_complete(node, future)
            if future.result() and future.result().success:
                node.get_logger().info('Lifecycle node activated successfully.')
                break
            else:
                node.get_logger().warn(f'Activation attempt {i+1} failed. Retrying...')
                time.sleep(arg.timeout)

    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
